"""
Django settings for DjangoTest project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-xqvgze&h0h*w(#-)$l@xkj0(ummoqgnx&gc=len1_t*dvzgt!@"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []
# 格式：应用名.模型名（你的SysUser在user应用下）Django 使用你的 SysUser 作为默认用户模型
AUTH_USER_MODEL = "user.SysUser"

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',#内置管理系统，可删除
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 跨域核心应用
    "corsheaders",
    # REST框架（可选，简化接口开发）
    "rest_framework",
    "rest_framework_simplejwt",  # Django 中集成 JWT（JSON Web Token）
    "user.apps.UserConfig",
    "menu.apps.MenuConfig",
    "feellist.apps.FeellistConfig",
    "role.apps.RoleConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # 跨域中间件（关键）
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 1. 允许跨域请求携带凭证（Cookie/Token等）
CORS_ALLOW_CREDENTIALS = True  # 关键：必须设为True
# 跨域配置（核心）
# 允许的前端域名（Vue默认运行在8080端口，根据实际修改）
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # 替换为你的前端地址
#     "http://127.0.0.1:5173",  # 两种形式都加上，避免兼容问题
# ]
# 允许的请求方法
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

ROOT_URLCONF = "DjangoTest.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "DjangoTest.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# MySQL数据库配置
# work配置
DATABASES = {
    "default": {
        # 数据库引擎（固定值）
        "ENGINE": "django.db.backends.mysql",
        # 数据库名（需提前在MySQL中创建，如手动执行 CREATE DATABASE django_feel DEFAULT CHARSET utf8mb4;）
        "NAME": "djangofeel",
        # MySQL用户名（默认root，生产环境建议创建专用用户）
        # "USER": "root",
        # MySQL密码（你的数据库密码）
        # "PASSWORD": "csy202ml!&",
        # 数据库地址（本地填localhost/127.0.0.1，远程填服务器IP）
        # "HOST": "localhost",
        # 端口（默认3306，若修改过需对应调整）
        "PORT": "3306",
        # 可选：连接参数（解决中文乱码、时区等问题）
        "OPTIONS": {
            # 字符集（utf8mb4兼容emoji，比utf8更全面）
            "charset": "utf8mb4",
            # MySQL8.0+需添加（解决认证方式问题）
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            # 连接超时（可选）
            "connect_timeout": 10,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# ========== 关键：引入本地配置 ==========
try:
    # 导入local_settings.py，覆盖上面的配置
    from .local_settings import *
except ImportError:
    # 若没有local_settings.py，抛出提示（避免忘记创建）
    raise ImportError("请在项目根目录创建local_settings.py，配置本地数据库密码/HOST等")
