# Generated by Django 6.0 on 2025-12-11 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('phonenuber', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入有效的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='用户号码')),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='评分不能低于0'), django.core.validators.MaxValueValidator(100, message='评分不能高于100')], verbose_name='评分')),
                ('netType', models.IntegerField(blank=True, choices=[(0, '5G'), (1, '4G'), (2, 'WiFi'), (3, '宽带'), (4, '其他')], null=True, verbose_name='网络类型')),
                ('cellScore', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='小区评分不能低于0'), django.core.validators.MaxValueValidator(100, message='小区评分不能高于100')], verbose_name='常驻小区评分')),
                ('cellName', models.CharField(blank=True, max_length=100, null=True, verbose_name='小区名称')),
                ('cellId', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='小区ID不能为负数')], verbose_name='小区ID')),
                ('sceneId', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联场景ID')),
                ('sceneType', models.CharField(blank=True, max_length=50, null=True, verbose_name='一级场景类型')),
                ('sceneSubType', models.CharField(blank=True, max_length=100, null=True, verbose_name='二级场景类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户评分表',
                'verbose_name_plural': '用户评分表',
                'db_table': 'user_score',
                'indexes': [models.Index(fields=['phonenuber'], name='user_score_phonenu_0b738b_idx'), models.Index(fields=['cellId'], name='user_score_cellId_974ef8_idx'), models.Index(fields=['sceneId'], name='user_score_sceneId_34f448_idx')],
            },
        ),
    ]
