# Generated by Django 6.0 on 2025-12-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='sceneName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='场景名称'),
        ),
    ]
