# Generated by Django 6.0 on 2025-12-27 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0002_userscore_scenename'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSceneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='地市')),
                ('base_station_id', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='基站ID不能为负数')], verbose_name='基站ID')),
                ('cell_id', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='小区ID不能为负数')], verbose_name='小区ID')),
                ('cell_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='小区级评分不能低于0'), django.core.validators.MaxValueValidator(100, message='小区级评分不能高于100')], verbose_name='小区级评分')),
                ('cell_user_avg_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='小区内用户均分不能低于0'), django.core.validators.MaxValueValidator(100, message='小区内用户均分不能高于100')], verbose_name='小区内用户均分')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='厂家')),
                ('contractor', models.CharField(blank=True, max_length=100, null=True, verbose_name='承建方')),
                ('has_complaint', models.IntegerField(blank=True, choices=[(0, '无投诉'), (1, '有投诉')], null=True, verbose_name='是否存在关联投诉工单')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('indicator', models.CharField(blank=True, max_length=50, null=True, verbose_name='指标')),
                ('scene_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联场景ID')),
                ('scene_level1', models.CharField(blank=True, max_length=50, null=True, verbose_name='一级场景')),
                ('scene_level2', models.CharField(blank=True, max_length=100, null=True, verbose_name='二级场景')),
                ('scene_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='场景名称')),
                ('indoor_outdoor', models.CharField(blank=True, choices=[('indoor', '室内'), ('outdoor', '室外')], max_length=10, null=True, verbose_name='室内室外')),
                ('area_type', models.CharField(blank=True, choices=[('rural', '农村'), ('town', '乡镇'), ('city', '城市'), ('county', '县城')], max_length=20, null=True, verbose_name='农村乡镇/城市县城')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小区数据表',
                'verbose_name_plural': '小区数据表',
                'db_table': 'network_scene_data',
                'indexes': [models.Index(fields=['date'], name='network_sce_date_a2858a_idx'), models.Index(fields=['cell_id'], name='network_sce_cell_id_0e9b59_idx'), models.Index(fields=['scene_id'], name='network_sce_scene_i_037627_idx'), models.Index(fields=['city'], name='network_sce_city_d9216b_idx')],
            },
        ),
    ]
