# Generated by Django 6.0 on 2026-01-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0003_networkscenedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkscenedata',
            name='scene_level1',
            field=models.CharField(blank=True, choices=[(0, '住宅小区'), (1, '重点商超'), (2, '政务中心'), (3, '医疗机构'), (4, '文旅景区'), (5, '商务楼宇及酒店'), (6, '交通枢纽'), (7, '高等学校')], max_length=50, null=True, verbose_name='一级场景'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='sceneType',
            field=models.IntegerField(blank=True, choices=[(0, '住宅小区'), (1, '重点商超'), (2, '政务中心'), (3, '医疗机构'), (4, '文旅景区'), (5, '商务楼宇及酒店'), (6, '交通枢纽'), (7, '高等学校')], max_length=50, null=True, verbose_name='一级场景类型'),
        ),
    ]
