# Generated by Django 6.0 on 2026-01-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0005_alter_networkscenedata_scene_level1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkscenedata',
            name='contractor',
            field=models.IntegerField(blank=True, choices=[(0, '电信'), (1, '联通')], null=True, verbose_name='承建方'),
        ),
    ]
