# Generated by Django 6.0 on 2026-01-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0006_alter_networkscenedata_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkscenedata',
            name='manufacturer',
            field=models.IntegerField(blank=True, choices=[(1, '华为'), (2, '中兴'), (7, '诺基亚'), (8, '大唐')], max_length=50, null=True, verbose_name='厂家'),
        ),
    ]
