# Generated by Django 6.0 on 2026-01-06 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0007_alter_networkscenedata_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkscenedata',
            name='base_station_id',
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='eci',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='基站ID不能为负数')], verbose_name='基站ID'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='eci',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='小区ID不能为负数')], verbose_name='小区ID'),
        ),
    ]
