# Generated by Django 6.0 on 2026-01-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0008_remove_networkscenedata_base_station_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='netType',
            field=models.IntegerField(blank=True, choices=[(0, '5G'), (1, '4G')], null=True, verbose_name='网络类型'),
        ),
    ]
