# Generated by Django 6.0 on 2026-01-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0009_alter_userscore_nettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkscenedata',
            name='city',
            field=models.IntegerField(blank=True, choices=[(11204, '九江'), (11201, '南昌'), (11207, '赣州'), (11210, '抚州'), (11208, '吉安'), (11209, '宜春'), (11205, '新余'), (11202, '景德镇'), (11206, '鹰潭'), (11203, '萍乡'), (11211, '上饶')], null=True, verbose_name='地市'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='city',
            field=models.IntegerField(blank=True, choices=[(11204, '九江'), (11201, '南昌'), (11207, '赣州'), (11210, '抚州'), (11208, '吉安'), (11209, '宜春'), (11205, '新余'), (11202, '景德镇'), (11206, '鹰潭'), (11203, '萍乡'), (11211, '上饶')], null=True, verbose_name='地市'),
        ),
    ]
