# Generated by Django 6.0 on 2026-01-08 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0010_alter_networkscenedata_city_alter_userscore_city'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userscore',
            name='user_score_phonenu_0b738b_idx',
        ),
        migrations.RemoveIndex(
            model_name='userscore',
            name='user_score_cellId_974ef8_idx',
        ),
        migrations.RemoveIndex(
            model_name='userscore',
            name='user_score_sceneId_34f448_idx',
        ),
        migrations.RenameField(
            model_name='userscore',
            old_name='phonenuber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='userscore',
            old_name='sceneId',
            new_name='scene_id',
        ),
        migrations.RemoveField(
            model_name='networkscenedata',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='networkscenedata',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='networkscenedata',
            name='scene_name',
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='area',
            field=models.IntegerField(blank=True, choices=[(0, '农村'), (1, '乡镇'), (2, '城市'), (3, '县城')], null=True, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='cellName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='小区名称'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='sceneName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='场景名称'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='cell_id',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='小区ID不能为负数')], verbose_name='cellID'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='cell_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='小区评分'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='net_type',
            field=models.IntegerField(blank=True, choices=[(0, '4G'), (1, '5G')], null=True, verbose_name='网络类型'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='scene_level1',
            field=models.IntegerField(blank=True, choices=[(0, '住宅小区'), (1, '重点商超'), (2, '政务中心'), (3, '医疗机构'), (4, '文旅景区'), (5, '商务楼宇及酒店'), (6, '交通枢纽'), (7, '高等学校')], null=True, verbose_name='一级场景'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='scene_level2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='二级场景'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='cell_id',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='小区ID不能为负数')], verbose_name='cellID'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='cell_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='小区评分'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='cell_user_avg_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='小区内用户均分'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='eci',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='基站ID不能为负数')], verbose_name='ECI'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='indoor_outdoor',
            field=models.IntegerField(blank=True, choices=[(0, '室外'), (1, '室内')], null=True, verbose_name='室内外'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='networkscenedata',
            name='manufacturer',
            field=models.IntegerField(blank=True, choices=[(1, '华为'), (2, '中兴'), (7, '诺基亚'), (8, '大唐')], null=True, verbose_name='厂家'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='eci',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='基站ID不能为负数')], verbose_name='ECI'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['phone_number'], name='user_score_phone_n_a53642_idx'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['cell_id'], name='user_score_cell_id_d83c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['scene_id'], name='user_score_scene_i_981e18_idx'),
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='cellId',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='cellScore',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='netType',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='sceneSubType',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='sceneType',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='score',
        ),
    ]
