# Generated by Django 6.0 on 2026-01-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feellist', '0011_remove_userscore_user_score_phonenu_0b738b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkscenedata',
            name='carrier_avg_noise_interference_health',
            field=models.FloatField(blank=True, null=True, verbose_name='载波平均噪声干扰-健康度'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='cqi_good_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='CQI优良率'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='dl_prb_utilization_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='下行PRB利用率_Mean'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='lte_service_drop_rate_qci1',
            field=models.FloatField(blank=True, null=True, verbose_name='LTE业务掉线率(QCI1)'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='mod3_interference_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='MOD3干扰比例'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='mod3_interference_sample_points_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='mod3干扰采样点数_Sum'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='mro_rsrp_ge_110_sample_points_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='MRO-RSRP≥-110采样点数_Sum'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='overlap_coverage_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='重叠覆盖比例'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='overlap_coverage_sample_points_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='重叠覆盖采样点数_Sum'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='qci1_dl_pdcp_sdu_loss_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='QCI1的下行PDCP SDU丢包率'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='qci1_ul_pdcp_sdu_loss_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='QCI1的上行PDCP SDU丢包率'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='rsrp_ge_110_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='RSRP>=-110比例'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='total_sample_point_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='总采样点_Sum'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='total_sample_points_mod3_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='总采样点数-mod3_Sum'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='total_sample_points_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='总采样点数_Sum'),
        ),
        migrations.AddField(
            model_name='networkscenedata',
            name='volte_connect_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='VOLTE接通率'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='MOS_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='平均MOS'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='MOS_dl_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='下行平均MOS'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='MOS_ul_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='上行平均MOS'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='MR_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级平均RSRP'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='MR_overlap_coverage_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级MR重叠覆盖率'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='MR_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='RSRP>=-110dBm占比'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='RSRQ_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级平均RSRQ'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='Ta_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Ta平均值'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='call_link_success_count_excl_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='呼叫建链成功次数（去除用户原因）'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='call_link_success_rate_excl_user',
            field=models.FloatField(blank=True, null=True, verbose_name='呼叫建链成功率（去除用户原因）'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='call_setup_req_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='呼叫建立请求次数'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='flu',
            field=models.FloatField(blank=True, null=True, verbose_name='流量(MB)'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='game_tcp_latency_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级游戏时延（TCP时延）ms'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='im_tcp_latency_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级即时通讯TCP时延ms'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='large_packet_rate_kbps',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级大包速率kbps'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='ul_interrupt_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级上行断续率'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='ul_one_way_audio_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级上行单通率'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='video_tcp_latency_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级视频TCP时延ms'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='web_tcp_latency_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='用户级浏览网页TCP时延ms'),
        ),
    ]
